### ISSUE TITLE
Algoritmo di Viterbi

### ISSUE THREAD

**Issue by TheEdoardo93** [TheEdoardo93/HMM-Mispelling#1]
Task da effettuare:
1) Controllare le matrici T, O e il vettore Pi
2) Estrarre la sequenza di stati più probabile (capire come leggerla - il verso)
3) Stamparla in modo decente

**Comment by ghost** [comment]
Per lo stamparla in modo decente io ho caricato le espressioni regolari nel file "cose utili". Per ora mi sto arrangiando così
